#!/bin/bash
set -eu

# This script starts the application.  It is used by the cucumber tests.

BASE_DIR="$( dirname "$0" )"

jar="$( echo "$BASE_DIR"/target/arrayChallenge2-1.0-SNAPSHOT.jar )"
exec java -jar "$jar" "$@"
